export const STATIONS = [
  "서울",
  "용산",
  "영등포",
  "광명",
  "수원",
  "평택지제",
  "천안아산",
  "오송",
  "대전",
  "김천구미",
  "구미",
  "서대구",
  "동대구",
  "경주",
  "울산",
  "부산",
  "행신",
  "청량리",
  "상봉",
  "양평",
  "만종",
  "서원주",
  "강릉",
  "정동진",
  "동해",
  "포항",
  "서대전",
  "계룡",
  "논산",
  "익산",
  "김제",
  "정읍",
  "광주송정",
  "나주",
  "목포",
  "전주",
  "남원",
  "곡성",
  "구례구",
  "순천",
  "여천",
  "여수엑스포",
  "밀양",
  "구포",
  "창원중앙",
  "창원",
  "마산",
  "진주",
  "공주",
  "안동",
  "영주",
  "제천",
  "충주",
  "단양",
  "영천",
  "경산",
  "왜관",
  "영동",
  "옥천",
  "조치원",
  "신탄진",
  "천안",
  "평택",
  "서빙고",
  "왕십리",
  "부강",
  "논산",
  "강경",
] as const;

export const POPULAR_ROUTES: Array<{ dep: string; arr: string; label: string }> = [
  { dep: "서울", arr: "부산", label: "서울 → 부산" },
  { dep: "서울", arr: "동대구", label: "서울 → 동대구" },
  { dep: "서울", arr: "대전", label: "서울 → 대전" },
  { dep: "용산", arr: "광주송정", label: "용산 → 광주송정" },
  { dep: "서울", arr: "강릉", label: "서울 → 강릉" },
  { dep: "동대구", arr: "서울", label: "동대구 → 서울" },
  { dep: "부산", arr: "서울", label: "부산 → 서울" },
  { dep: "광명", arr: "부산", label: "광명 → 부산" },
];

export function filterStations(query: string): string[] {
  const q = query.trim();
  if (!q) return [...STATIONS];
  return STATIONS.filter((name) => name.includes(q));
}
